### ISSUE TITLE
[Feature Request] Ability to hide apps

### ISSUE THREAD

**Issue by esmoak** [stanipintjuk/Silverfish#75] opened 2018-12-07 18:23 UTC
Not sure if Silverfish is developed anymore...

I would love to see a feature to hide apps without the app having to be in an "other" tab.

Perhaps: 
-Long press app to hide.
-Toggle hidden app visibility in the right drawer. 
-Maybe have a pin lock option to secure hidden apps.

Thanks.

**Comment by Lonami** [comment] 2018-12-08 00:59
Duplicate of #10 and #33. Thanks for the interest though!

**Closed as completed by Lonami** 2018-12-08 00:59 UTC
