### ISSUE TITLE
Fix widget change method

### ISSUE THREAD

**Issue by yllwboy** [stanipintjuk/Silverfish#28] opened 2016-08-27 08:35 UTC
Some widgets I have fill the entire dedicated widget space (or at least a significant portion of it), making it impossible for me to hold in order to change. The only fix I have found to this is erasing all the launcher data, a rather bold "solution". Please add something like the option to change the widget by clicking on the "options" button on your phone or something like that.

**Comment by Lonami** [comment] 2016-08-27 09:11
This should already be fixed. Please make sure you hold your finger _without moving it **at all**_. If you still don't manage to trigger the widget selection, we would appreciate either a video (showing the finger on the screen) or the exact types to reproduce.

**Comment by yllwboy** [comment] 2016-08-27 18:10
It is not fixed yet, I can confirm. While using the Dual Clock Samsung widget for example, holding it without moving will only select the widget and will open the Dual Clock settings. You should normally be able to reproduce this with any interactive widget that fills the whole widget space, another example would be the Etar calendar widget.

**Comment by Lonami** [comment] 2016-08-27 19:56
Another possibility is that the Dual Clock Samsung widget handles the long click itself, hence not allowing Silverfish to capture the event. I'm not sure, but it is another possibility.

**Comment by yllwboy** [comment] 2016-08-27 20:05
You should try to reproduce it with the Etar app which is available on F-Droid. The same thing happens: long click is processed as a simple click, therefore not allowing me to change the widget. It might be a ROM/device-specific issue but it shouldn't be too complicated to add the option to change the widget by pressing the hardware "options" button on the phone...

**Comment by stanipintjuk** [comment] 2016-08-27 22:33
I have tried with the Etar widget and cannot replicate this bug. What phone/rom do you have? Maybe I can get my hands on a similar setup and test some more.

I am planning to add some kind of options activity, but I am not quite sure how to make the users access it since there is no "options" button on new Android phones anymore.
Any suggestions?

**Comment by Lonami** [comment] 2016-08-27 22:57
Tried with Etar widget. Yes, it's a bit hard not to move the finger _at all_; but it's possible (and hence, I'm able to change the widget too).

>  Any suggestions?

Should we bring back the infamous swipe offset? It wasn't that bad... ;)

**Comment by yllwboy** [comment] 2016-08-28 12:24
I have a Samsung S3 Neo running the stock ROM non-rooted.

I'd suggest still adding the "options" button way to access that for phones that support it and for those that don't, just have some alternative method like a options icon on the bottom right corner or something.

Well, I'm going to try once again but I could only change the widget if I had access to the space not occupied by the widget. Anyway, it is unnecessarily hard to change the widget so there's place for some improvement here.

**Comment by yllwboy** [comment] 2016-08-28 12:28
I have tested once again and I have managed to change the widget now. However, it is still not very user-friendly, I think there should be an alternative way to change it.

**Comment by Lonami** [comment] 2016-08-28 13:38
After some more internal work, a `Settings` activity will be later implemented. There you will be able not to only change the widget, but also set, adjust or tweak other settings.

**Comment by Lonami** [comment] 2016-12-14 19:43
Cleaning up issues, closing this one since it was implemented on [commit#5a377c](https://github.com/stanipintjuk/Silverfish/commit/5a377cb1682951714f145e2100dc7be7131d99c6).

**Closed as completed by Lonami** 2016-12-14 19:43 UTC
